name: Python Continuous Integration (CI)

# Trigger the workflow on pushes to the main branch and on all pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Define a single job named 'build'
jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    # Define the steps for the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Step 2: Set up the Python environment (using a specific version)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # Step 3: Install dependencies from requirements.txt
      # This step is CRITICAL for installing 'pytest' and other necessary packages
      - name: Install dependencies
        run: |
          # Upgrade pip to the latest version
          python -m pip install --upgrade pip
          # Install all dependencies listed in your requirements.txt
          pip install -r requirements.txt
          
      # Step 4: Run the test suite
      - name: Run tests with Pytest
        # This command will execute all tests found by pytest
        run: |
          pytest
          
      # Step 5: (Optional) A simple example of running a script
      # NOTE: You MUST change 'my_main_script.py' to the actual name 
      # and path of your script, or remove this step if not needed.
      - name: Execute a sample script
        run: |
          echo "Test run complete. Starting sample script..."
          # Example: python src/my_main_script.py
          # Replace with your actual script command:
          echo "Script execution step is a placeholder."
