name: Python Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Download your code
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
        
      # Step 2: Set up the Python environment
      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # Step 3: INSTALL THE PYTEST TOOL (The Fix!)
      - name: 3. Install Pytest
        run: pip install pytest
          
      # Step 4: Run the test suite
      - name: 4. Run tests
        run: pytest
