name: CI on Ubuntu

# 1. Define when the workflow runs (triggers)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 2. Define the jobs that make up the workflow
jobs:
  build-and-test:
    # 3. Specify the runner operating system
    runs-on: ubuntu-latest

    # 4. Define a sequence of steps for the job
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run a multi-line script on the Ubuntu runner
      - name: Display system information
        run: |
          echo "Running on the following Ubuntu version:"
          cat /etc/os-release
          echo "The current working directory is: $(pwd)"
          echo "The runner's home directory is: $HOME"
          echo "The current user is: $(whoami)"

      # Install a package using apt (a common Ubuntu package manager)
      - name: Install a utility (e.g., jq)
        run: sudo apt-get update && sudo apt-get install -y jq

      # Run a simple test command
      - name: Run a test
        run: |
          echo "All checks passed!"
          jq --version
